services:
  backend:
    build: .
    container_name: taro_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taro_db
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  db:
    image: postgres:18-alpine
    container_name: taro_db
    environment:
      POSTGRES_DB: taro_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d taro_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

volumes:
  pgdata:
    name: taro_pgdata
