services:
  nginx:
    image: nginx:alpine
    container_name: taro_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: always
    networks:
      - taro_network

  backend:
    build: .
    container_name: taro_app
    depends_on:
      db:
        condition: service_healthy
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taro_db
      SPRING_DATASOURCE_USERNAME: taro_user
      SPRING_DATASOURCE_PASSWORD: SuperUser!testPas
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    networks:
      - taro_network

  db:
    image: postgres:18-alpine
    container_name: taro_db
    environment:
      POSTGRES_DB: taro_db
      POSTGRES_USER: taro_user
      POSTGRES_PASSWORD: SuperUser!testPas
    volumes:
      - pgdata:/var/lib/postgresql
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U taro_user -d taro_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    networks:
      - taro_network

volumes:
  pgdata:
    name: taro_pgdata

networks:
  taro_network:
    driver: bridge
