spring.application.name=TARO

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5431/taro_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

# Настройки для Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

# Настройки кэширования Caffeine
spring.cache.caffeine.spec=expireAfterWrite=60m

# Базовый паттерн логирования в консоль
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n

spring.profiles.active=dev
