# Строгий запрет на любые изменения схемы базы данных со стороны Hibernate
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=validate

# Красивое логирование SQL-запросов в консоль для отладки
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG

# Полезные логи работы Liquibase в режиме разработки
logging.level.liquibase=INFO
