# Строгий запрет на любые изменения схемы базы данных со стороны Hibernate
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none

# Логирование
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.SQL=ERROR
logging.level.root=WARN

# Позволяет Spring правильно обрабатывать HTTPS заголовки от Nginx
server.forward-headers-strategy=native

# Оптимизация пула соединений базы данных HikariCP
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000
