spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

# Логирование
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.SQL=ERROR

# Позволяет Spring правильно обрабатывать HTTPS заголовки от Nginx
server.forward-headers-strategy=native
