logging.level.scari.corp.taro=DEBUG
# Чтобы видеть, как Spring работает с кэшем внутри
logging.level.org.springframework.cache=TRACE

logging.pattern.console=%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n
