spring.application.name=TARO

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.cache.caffeine.spec=expireAfterWrite=60m

logging.pattern.console=%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n
